namespace DevFlow.Application.Common.Interfaces;

/// <summary>
/// Builds the clickable password reset URL. Behind an interface for the same
/// reason as <see cref="IEmailVerificationLinkBuilder"/>: the frontend base URL
/// is configuration the application layer must not read.
/// </summary>
/// <remarks>
/// Unlike the verification builder this one does not mint the token. A reset
/// token has to be persisted (single-use) and the handler has to hash exactly
/// what is emailed, so the token is generated by
/// <see cref="IPasswordResetTokenGenerator"/> and passed in already hashed
/// nowhere — this method only wraps a raw token in a URL.
/// </remarks>
public interface IPasswordResetLinkBuilder
{
    /// <summary>Returns the full link for a raw, not-yet-persisted token.</summary>
    string Build(string token);
}
